Fix a couple of deployment bugs and an error notifying enhancement
timblair/slack-archivebot pull request #3
Opened 2016-10-21 13:00 UTC by barryf

1. Add repo (template) to Heroku deploy button link.
2. Take out `bundle` command in app package which was causing an error.
3. Specify a channel/user to notify in case things go wrong.

(3) was added when initial deployment crashed: it was trying to archive a channel with a single-channel user and borking. Getting a DM means I realise it's broken rather than silently failing each hour.

2016-11-07 12:54 UTC, timblair requested changes
I like the ideas.  Just a few small bits to go back to.

2016-11-07 12:54 UTC, timblair commented on README.md
> +[![Deploy to Heroku](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/timblair/slack-archivebot)
Please could you move the URLs to reference links to avoid the long line.

2016-11-07 12:54 UTC, timblair commented on README.md
> +* `ARCHIVEBOT_NOTIFY`: a Slack user or channel (e.g. `#general` or `@tblair`) to notify when something goes wrong.
Please wrap this line at 78 characters (or after the closing bracket, whatever that point it).

2016-11-07 12:54 UTC, timblair commented on bot.go
> +				message := fmt.Sprintf("Error archiving channel #%s (%s): %s\n", c.Name, c.Id, err)
I appreciate that we're quite nested here, but is there a nice way to split this line to keep within the line length?

2016-11-07 12:54 UTC, timblair commented on bot.go
> +				api.PostMessage(onErrorNotify, message, params)
I'm guessing that this API call will fail if the `ARCHIVEBOT_NOTIFY` environment variable is empty, but that the error will be ignored?  I'd rather be explicit about only attempting the notification if there's a user/channel defined, and it should also log an error if the call fails.

2016-11-09 14:11 UTC, barryf commented
I've pushed new commits that address your requests. Can you review?

2016-11-09 21:00 UTC, timblair requested changes
One last thing, then it looks good to merge to me.

2016-11-09 21:00 UTC, timblair commented on bot.go
> +					api.PostMessage(onErrorNotify, message, params)
Please log a message if this call fails.

2016-11-16 13:48 UTC, timblair approved these changes

2016-11-16 13:49 UTC, merged